/* سعرلي سوريا - التصنيفات + النواة المشتركة للإضافات */
(function(){
'use strict';
if(!window.supabase){console.error('Supabase JS غير محمل');return;}
const URL='https://ovocwugezuddbwypzteg.supabase.co';
const KEY='sb_publishable_THEl1NqFWWRUImYpTLxu9g_iGM03Nsz';
const client=supabase.createClient(URL,KEY);
const core=window.SareeFeatureCore=window.SareeFeatureCore||{};
core.client=client; core.url=URL;
core.escape=core.escape||function(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));};
core.fmt=core.fmt||function(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});};
core.wa=core.wa||function(v){v=String(v||'').trim();if(!v)return '';if(/^https?:\/\//i.test(v))return v;const d=v.replace(/\D/g,'');return d?'https://wa.me/'+d:'';};
core.cache=core.cache||{};
function style(){if(document.getElementById('saree-cat-style'))return;const s=document.createElement('style');s.id='saree-cat-style';s.textContent=`.saree-cat-card{cursor:pointer}.saree-cat-card:hover{border-color:#35d07f}.saree-modal{position:fixed;inset:0;background:rgba(0,0,0,.72);z-index:9999;display:flex;align-items:center;justify-content:center;padding:14px}.saree-modal>div{width:min(920px,100%);max-height:92vh;overflow:auto;background:#10181c;border:1px solid #304047;border-radius:20px;padding:18px}.saree-cat-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.saree-product-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}@media(max-width:650px){.saree-product-grid{grid-template-columns:1fr}}` ;document.head.appendChild(s);}
function modal(){let m=document.getElementById('sareeCategoryModal');if(m)return m;m=document.createElement('div');m.id='sareeCategoryModal';m.className='saree-modal hidden';m.innerHTML='<div><div class="saree-cat-head"><div><h2 id="sareeCatTitle">التصنيف</h2><div id="sareeCatCount" class="muted"></div></div><button class="btn secondary" id="sareeCatClose">×</button></div><input id="sareeCatSearch" placeholder="ابحث داخل هذا التصنيف..."><div id="sareeCatProducts" class="saree-product-grid" style="margin-top:12px"></div></div>';document.body.appendChild(m);m.querySelector('#sareeCatClose').onclick=()=>m.classList.add('hidden');m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')});m.querySelector('#sareeCatSearch').addEventListener('input',()=>renderModal());return m;}
let activeCategory='';let activeProducts=[];
function renderModal(){const m=modal(),q=(m.querySelector('#sareeCatSearch').value||'').trim().toLowerCase();const list=activeProducts.filter(p=>![p.name,p.brand,p.unit,p.description].join(' ').toLowerCase().includes(q)===false);m.querySelector('#sareeCatCount').textContent=`${activeProducts.length} منتجات ضمن تصنيف «${activeCategory}»`;m.querySelector('#sareeCatProducts').innerHTML=list.map(p=>{const img=p.image_url?`<img class="img" src="${core.escape(p.image_url)}">`:'';return `<div class="card">${img}<span class="pill">${core.escape(p.category||'عام')}</span><div class="name">${core.escape(p.name)}</div><div class="muted">${core.escape(p.unit||'')} ${p.brand?'• '+core.escape(p.brand):''}</div><button class="btn primary" onclick="details('${p.id}')">تفاصيل الأسعار</button></div>`}).join('')||'<div class="card muted">لا توجد منتجات مطابقة.</div>';}
async function openCategory(category){activeCategory=category||'عام';const m=modal();m.classList.remove('hidden');m.querySelector('#sareeCatTitle').textContent='منتجات تصنيف: '+activeCategory;m.querySelector('#sareeCatSearch').value='';m.querySelector('#sareeCatProducts').innerHTML='<div class="card muted">جاري تحميل المنتجات...</div>';const {data,error}=await client.from('products').select('*').eq('active',true).eq('category',activeCategory).order('name');if(error){m.querySelector('#sareeCatProducts').innerHTML='<div class="card dangerbox">تعذر تحميل منتجات التصنيف: '+core.escape(error.message)+'</div>';return;}activeProducts=data||[];renderModal();}
function bind(){style();modal();const cats=document.getElementById('cats');if(!cats)return;cats.querySelectorAll('.card').forEach(card=>{if(card.dataset.sareeBound)return;card.dataset.sareeBound='1';card.classList.add('saree-cat-card');card.addEventListener('click',e=>{if(e.target.closest('button,a,input,select'))return;const pill=card.querySelector('.pill');const text=pill?.textContent?.trim();if(text)openCategory(text);});});}
function patchRenderCategories(){if(typeof window.renderCategories!=='function'||window.__sareeCatPatch)return;const orig=window.renderCategories;window.renderCategories=function(){const r=orig.apply(this,arguments);setTimeout(bind,0);return r;};window.__sareeCatPatch=true;setTimeout(bind,0);}
window.sareeOpenCategoryProducts=openCategory;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchRenderCategories,{once:true});else patchRenderCategories();
})();
