-- =============================================
-- سعرلي سوريا — نظام الشركات الكامل
-- يُشغّل بعد supabase_fix.sql
-- =============================================

alter table public.profiles add column if not exists company_id uuid;

alter table public.companies add column if not exists allow_product_images boolean not null default true;
alter table public.companies add column if not exists allow_product_questions boolean not null default false;

-- شركة كيان مستقل: المستخدمون المرتبطون بالشركة والصلاحيات
create table if not exists public.company_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  can_manage_products boolean not null default false,
  can_edit_products boolean not null default false,
  can_delete_products boolean not null default false,
  can_manage_categories boolean not null default false,
  can_manage_settings boolean not null default false,
  can_view_orders boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_users_company_idx on public.company_users(company_id);
create index if not exists company_users_active_idx on public.company_users(active);

create table if not exists public.company_account_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  requested_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  company_id uuid references public.companies(id) on delete set null,
  rejection_reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);
create index if not exists company_account_requests_status_idx on public.company_account_requests(status);

-- تصنيفات منتجات الشركات
create table if not exists public.company_categories (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id,name)
);
create index if not exists company_categories_company_idx on public.company_categories(company_id);

-- منتجات مستقلة للشركة. السعر اختياري بالكامل.
create table if not exists public.company_products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  brand text,
  unit text,
  category text,
  category_id uuid references public.company_categories(id) on delete set null,
  barcode text,
  description text,
  image_url text,
  price_new numeric(14,2),
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists company_products_company_idx on public.company_products(company_id);
create index if not exists company_products_barcode_idx on public.company_products(barcode);
create index if not exists company_products_category_idx on public.company_products(category);
create unique index if not exists company_products_company_barcode_uq
  on public.company_products(company_id, barcode)
  where barcode is not null and length(trim(barcode)) > 0;

-- زيارات صفحات الشركات
create table if not exists public.company_visitor_visits (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  visitor_id text,
  created_at timestamptz not null default now()
);
create index if not exists company_visits_company_idx on public.company_visitor_visits(company_id);
create index if not exists company_visits_created_idx on public.company_visitor_visits(created_at);

-- FK profile -> company
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'profiles_company_id_fkey'
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_company_id_fkey
      FOREIGN KEY (company_id) REFERENCES public.companies(id)
      ON DELETE SET NULL;
  END IF;
END $$;

-- حماية الحقول الحساسة للملف الشخصي من التعديل الذاتي
create or replace function public.protect_profile_privilege_fields()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is not null and auth.uid() <> old.id and not public.is_admin() then
    raise exception 'غير مسموح بتعديل حساب مستخدم آخر';
  end if;
  if auth.uid() = old.id and not public.is_admin() then
    if new.role is distinct from old.role
       or new.store_id is distinct from old.store_id
       or new.company_id is distinct from old.company_id
       or new.can_edit_prices is distinct from old.can_edit_prices
       or new.verified is distinct from old.verified then
      raise exception 'لا يمكن للحساب تعديل الدور أو الربط أو الصلاحيات بنفسه';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists protect_profile_privilege_fields on public.profiles;
create trigger protect_profile_privilege_fields
before update on public.profiles
for each row execute function public.protect_profile_privilege_fields();

-- أدوات الصلاحيات
create or replace function public.is_company_member(p_company_id uuid)
returns boolean
language sql
security definer
set search_path=public
stable
as $$
  select exists(
    select 1 from public.company_users cu
    where cu.user_id=auth.uid()
      and cu.company_id=p_company_id
      and cu.active=true
  );
$$;

create or replace function public.company_can(p_company_id uuid, p_permission text)
returns boolean
language sql
security definer
set search_path=public
stable
as $$
  select exists(
    select 1 from public.company_users cu
    where cu.user_id=auth.uid()
      and cu.company_id=p_company_id
      and cu.active=true
      and (
        (p_permission='manage_products' and cu.can_manage_products)
        or (p_permission='edit_products' and cu.can_edit_products)
        or (p_permission='delete_products' and cu.can_delete_products)
        or (p_permission='manage_categories' and cu.can_manage_categories)
        or (p_permission='manage_settings' and cu.can_manage_settings)
        or (p_permission='view_orders' and cu.can_view_orders)
      )
  );
$$;

revoke all on function public.is_company_member(uuid) from public;
grant execute on function public.is_company_member(uuid) to anon, authenticated;
revoke all on function public.company_can(uuid,text) from public;
grant execute on function public.company_can(uuid,text) to authenticated;

-- RLS
alter table public.company_users enable row level security;
alter table public.company_account_requests enable row level security;
alter table public.company_categories enable row level security;
alter table public.company_products enable row level security;
alter table public.company_visitor_visits enable row level security;

DROP POLICY IF EXISTS "company users self read" ON public.company_users;
DROP POLICY IF EXISTS "company users admin manage" ON public.company_users;
create policy "company users self read" on public.company_users
for select to authenticated
using (user_id=auth.uid() or public.is_admin());
create policy "company users admin manage" on public.company_users
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

DROP POLICY IF EXISTS "company request self" ON public.company_account_requests;
DROP POLICY IF EXISTS "company request admin" ON public.company_account_requests;
create policy "company request self" on public.company_account_requests
for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy "company request admin" on public.company_account_requests
for all to authenticated using (public.is_admin()) with check (public.is_admin());

DROP POLICY IF EXISTS "public read active company categories" ON public.company_categories;
DROP POLICY IF EXISTS "company members read categories" ON public.company_categories;
DROP POLICY IF EXISTS "admin manage company categories" ON public.company_categories;
create policy "public read active company categories" on public.company_categories
for select to anon,authenticated
using (active=true and exists(select 1 from public.companies c where c.id=company_id and c.active=true) or public.is_admin());
create policy "company members read categories" on public.company_categories
for select to authenticated using (public.is_company_member(company_id));
create policy "admin manage company categories" on public.company_categories
for all to authenticated using (public.is_admin()) with check (public.is_admin());

DROP POLICY IF EXISTS "public read active company products" ON public.company_products;
DROP POLICY IF EXISTS "company members read own products" ON public.company_products;
DROP POLICY IF EXISTS "admin manage company products" ON public.company_products;
create policy "public read active company products" on public.company_products
for select to anon,authenticated
using (active=true and exists(select 1 from public.companies c where c.id=company_id and c.active=true) or public.is_admin());
create policy "company members read own products" on public.company_products
for select to authenticated using (public.is_company_member(company_id));
create policy "admin manage company products" on public.company_products
for all to authenticated using (public.is_admin()) with check (public.is_admin());

DROP POLICY IF EXISTS "company visits public insert" ON public.company_visitor_visits;
DROP POLICY IF EXISTS "company visits admin read" ON public.company_visitor_visits;
create policy "company visits public insert" on public.company_visitor_visits
for insert to anon,authenticated with check (exists(select 1 from public.companies c where c.id=company_id and c.active=true));
create policy "company visits admin read" on public.company_visitor_visits
for select to authenticated using (public.is_admin());

-- طلب ربط حساب شركة
create or replace function public.request_company_account(p_requested_name text default null)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare v_id uuid;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  insert into public.company_account_requests(user_id,requested_name,status)
  values(auth.uid(), nullif(trim(coalesce(p_requested_name,'')),''), 'pending')
  on conflict (user_id) do update set
    requested_name=coalesce(excluded.requested_name, public.company_account_requests.requested_name),
    status=case when public.company_account_requests.status='rejected' then 'pending' else public.company_account_requests.status end,
    rejection_reason=null;
  select id into v_id from public.company_account_requests where user_id=auth.uid();
  return v_id;
end $$;
revoke all on function public.request_company_account(text) from public;
grant execute on function public.request_company_account(text) to authenticated;

-- المدير: قائمة طلبات حسابات الشركات
create or replace function public.admin_list_company_account_requests()
returns table(
  id uuid, user_id uuid, requested_name text, email text, status text,
  company_id uuid, company_name text, created_at timestamptz, rejection_reason text
)
language sql
security definer
set search_path=public
stable
as $$
  select r.id,r.user_id,r.requested_name,u.email,r.status,r.company_id,c.name,r.created_at,r.rejection_reason
  from public.company_account_requests r
  join auth.users u on u.id=r.user_id
  left join public.companies c on c.id=r.company_id
  where public.is_admin()
  order by r.created_at desc;
$$;
revoke all on function public.admin_list_company_account_requests() from public;
grant execute on function public.admin_list_company_account_requests() to authenticated;

-- المدير: ربط حساب الشركة بالشركة وتحديد كامل الصلاحيات
create or replace function public.admin_link_company_account(
  p_request_id uuid,
  p_company_id uuid,
  p_can_manage_products boolean default false,
  p_can_edit_products boolean default false,
  p_can_delete_products boolean default false,
  p_can_manage_categories boolean default false,
  p_can_manage_settings boolean default false,
  p_can_view_orders boolean default false
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_user uuid;
begin
  if not public.is_admin() then raise exception 'المدير فقط يستطيع ربط حسابات الشركات'; end if;
  select user_id into v_user from public.company_account_requests where id=p_request_id;
  if v_user is null then raise exception 'طلب حساب الشركة غير موجود'; end if;
  if not exists(select 1 from public.companies where id=p_company_id) then raise exception 'الشركة غير موجودة'; end if;

  insert into public.company_users(user_id,company_id,can_manage_products,can_edit_products,can_delete_products,can_manage_categories,can_manage_settings,can_view_orders,active)
  values(v_user,p_company_id,p_can_manage_products,p_can_edit_products,p_can_delete_products,p_can_manage_categories,p_can_manage_settings,p_can_view_orders,true)
  on conflict(user_id) do update set
    company_id=excluded.company_id,
    can_manage_products=excluded.can_manage_products,
    can_edit_products=excluded.can_edit_products,
    can_delete_products=excluded.can_delete_products,
    can_manage_categories=excluded.can_manage_categories,
    can_manage_settings=excluded.can_manage_settings,
    can_view_orders=excluded.can_view_orders,
    active=true,
    updated_at=now();

  update public.profiles set role='company',company_id=p_company_id,store_id=null,can_edit_prices=false,verified=true where id=v_user;
  update public.company_account_requests set status='approved',company_id=p_company_id,reviewed_at=now(),reviewed_by=auth.uid() where id=p_request_id;
end $$;
revoke all on function public.admin_link_company_account(uuid,uuid,boolean,boolean,boolean,boolean,boolean,boolean) from public;
grant execute on function public.admin_link_company_account(uuid,uuid,boolean,boolean,boolean,boolean,boolean,boolean) to authenticated;

create or replace function public.admin_set_company_permissions(
  p_user_id uuid,
  p_can_manage_products boolean,
  p_can_edit_products boolean,
  p_can_delete_products boolean,
  p_can_manage_categories boolean,
  p_can_manage_settings boolean,
  p_can_view_orders boolean,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'المدير فقط يستطيع تعديل الصلاحيات'; end if;
  update public.company_users set
    can_manage_products=p_can_manage_products,
    can_edit_products=p_can_edit_products,
    can_delete_products=p_can_delete_products,
    can_manage_categories=p_can_manage_categories,
    can_manage_settings=p_can_manage_settings,
    can_view_orders=p_can_view_orders,
    active=p_active,
    updated_at=now()
  where user_id=p_user_id;
  if not found then raise exception 'حساب الشركة غير مرتبط'; end if;
end $$;
revoke all on function public.admin_set_company_permissions(uuid,boolean,boolean,boolean,boolean,boolean,boolean,boolean) from public;
grant execute on function public.admin_set_company_permissions(uuid,boolean,boolean,boolean,boolean,boolean,boolean,boolean) to authenticated;

create or replace function public.admin_unlink_company_account(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'المدير فقط'; end if;
  delete from public.company_users where user_id=p_user_id;
  update public.profiles set role='user',company_id=null,store_id=null,can_edit_prices=false where id=p_user_id;
end $$;
revoke all on function public.admin_unlink_company_account(uuid) from public;
grant execute on function public.admin_unlink_company_account(uuid) to authenticated;

-- وظائف إدخال المنتجات من حساب الشركة
create or replace function public.company_add_product(
  p_name text,
  p_brand text default null,
  p_unit text default null,
  p_category text default null,
  p_category_id uuid default null,
  p_barcode text default null,
  p_description text default null,
  p_image_url text default null,
  p_price_new numeric default null
)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare v_company uuid; v_id uuid;
begin
  select company_id into v_company from public.company_users where user_id=auth.uid() and active=true;
  if v_company is null then raise exception 'حساب الشركة غير مرتبط'; end if;
  if not public.company_can(v_company,'manage_products') then raise exception 'لا توجد صلاحية إضافة المنتجات'; end if;
  if trim(coalesce(p_name,''))='' then raise exception 'اسم المادة مطلوب'; end if;
  if p_barcode is not null and trim(p_barcode)='' then p_barcode=null; end if;
  if p_price_new is not null and p_price_new < 0 then raise exception 'السعر غير صالح'; end if;
  insert into public.company_products(company_id,name,brand,unit,category,category_id,barcode,description,image_url,price_new,active,created_by)
  values(v_company,trim(p_name),nullif(trim(p_brand),''),nullif(trim(p_unit),''),nullif(trim(p_category),''),p_category_id,nullif(trim(p_barcode),''),p_description,p_image_url,p_price_new,true,auth.uid())
  returning id into v_id;
  return v_id;
end $$;
revoke all on function public.company_add_product(text,text,text,text,uuid,text,text,text,numeric) from public;
grant execute on function public.company_add_product(text,text,text,text,uuid,text,text,text,numeric) to authenticated;

create or replace function public.company_update_product(
  p_id uuid,
  p_name text,
  p_brand text default null,
  p_unit text default null,
  p_category text default null,
  p_category_id uuid default null,
  p_barcode text default null,
  p_description text default null,
  p_image_url text default null,
  p_price_new numeric default null,
  p_active boolean default true
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_company uuid;
begin
  select company_id into v_company from public.company_users where user_id=auth.uid() and active=true;
  if v_company is null then raise exception 'حساب الشركة غير مرتبط'; end if;
  if not public.company_can(v_company,'edit_products') and not public.company_can(v_company,'manage_products') then raise exception 'لا توجد صلاحية تعديل المنتجات'; end if;
  update public.company_products set name=trim(p_name),brand=nullif(trim(p_brand),''),unit=nullif(trim(p_unit),''),category=nullif(trim(p_category),''),category_id=p_category_id,barcode=nullif(trim(p_barcode),''),description=p_description,image_url=p_image_url,price_new=p_price_new,active=p_active,updated_at=now()
  where id=p_id and company_id=v_company;
  if not found then raise exception 'المنتج غير موجود'; end if;
end $$;
revoke all on function public.company_update_product(uuid,text,text,text,text,uuid,text,text,text,numeric,boolean) from public;
grant execute on function public.company_update_product(uuid,text,text,text,uuid,text,text,text,numeric,boolean) to authenticated;

create or replace function public.company_delete_product(p_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_company uuid;
begin
  select company_id into v_company from public.company_users where user_id=auth.uid() and active=true;
  if v_company is null then raise exception 'حساب الشركة غير مرتبط'; end if;
  if not public.company_can(v_company,'delete_products') and not public.company_can(v_company,'manage_products') then raise exception 'لا توجد صلاحية حذف المنتجات'; end if;
  update public.company_products set active=false,updated_at=now() where id=p_id and company_id=v_company;
  if not found then raise exception 'المنتج غير موجود'; end if;
end $$;
revoke all on function public.company_delete_product(uuid) from public;
grant execute on function public.company_delete_product(uuid) to authenticated;

create or replace function public.company_add_category(p_name text)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare v_company uuid; v_id uuid;
begin
  select company_id into v_company from public.company_users where user_id=auth.uid() and active=true;
  if v_company is null then raise exception 'حساب الشركة غير مرتبط'; end if;
  if not public.company_can(v_company,'manage_categories') then raise exception 'لا توجد صلاحية إدارة التصنيفات'; end if;
  insert into public.company_categories(company_id,name,active) values(v_company,trim(p_name),true) returning id into v_id;
  return v_id;
end $$;
revoke all on function public.company_add_category(text) from public;
grant execute on function public.company_add_category(text) to authenticated;

create or replace function public.company_toggle_category(p_id uuid,p_active boolean)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_company uuid;
begin
  select company_id into v_company from public.company_users where user_id=auth.uid() and active=true;
  if v_company is null or not public.company_can(v_company,'manage_categories') then raise exception 'لا توجد صلاحية'; end if;
  update public.company_categories set active=p_active,updated_at=now() where id=p_id and company_id=v_company;
end $$;
revoke all on function public.company_toggle_category(uuid,boolean) from public;
grant execute on function public.company_toggle_category(uuid,boolean) to authenticated;

create or replace function public.record_company_visit(p_company_id uuid,p_visitor_id text default null)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.companies where id=p_company_id and active=true) then return; end if;
  insert into public.company_visitor_visits(company_id,visitor_id) values(p_company_id,nullif(trim(coalesce(p_visitor_id,'')),''));
end $$;
revoke all on function public.record_company_visit(uuid,text) from public;
grant execute on function public.record_company_visit(uuid,text) to anon,authenticated;

create or replace function public.admin_company_visitor_stats(p_company_id uuid)
returns table(total_visits bigint, unique_visitors bigint)
language sql
security definer
set search_path=public
stable
as $$
  select count(*)::bigint,
         count(distinct nullif(visitor_id,''))::bigint
  from public.company_visitor_visits
  where company_id=p_company_id and public.is_admin();
$$;
revoke all on function public.admin_company_visitor_stats(uuid) from public;
grant execute on function public.admin_company_visitor_stats(uuid) to authenticated;

create or replace function public.admin_company_visitor_counts()
returns table(company_id uuid,total_visits bigint,unique_visitors bigint)
language sql
security definer
set search_path=public
stable
as $$
  select company_id,count(*)::bigint,count(distinct nullif(visitor_id,''))::bigint
  from public.company_visitor_visits
  where public.is_admin()
  group by company_id;
$$;
revoke all on function public.admin_company_visitor_counts() from public;
grant execute on function public.admin_company_visitor_counts() to authenticated;

notify pgrst, 'reload schema';

-- قائمة الحسابات المرتبطة للمدير مع البريد الإلكتروني
create or replace function public.admin_list_company_users()
returns table(
  id uuid, user_id uuid, email text, company_id uuid, company_name text,
  can_manage_products boolean, can_edit_products boolean, can_delete_products boolean,
  can_manage_categories boolean, can_manage_settings boolean, can_view_orders boolean, active boolean
)
language sql
security definer
set search_path=public
stable
as $$
  select cu.id,cu.user_id,u.email,cu.company_id,c.name,
         cu.can_manage_products,cu.can_edit_products,cu.can_delete_products,
         cu.can_manage_categories,cu.can_manage_settings,cu.can_view_orders,cu.active
  from public.company_users cu
  join auth.users u on u.id=cu.user_id
  left join public.companies c on c.id=cu.company_id
  where public.is_admin()
  order by c.name,u.email;
$$;
revoke all on function public.admin_list_company_users() from public;
grant execute on function public.admin_list_company_users() to authenticated;

notify pgrst, 'reload schema';
