/* سعرلي سوريا — طلبات واتساب
   ميزة مستقلة: لا تعمل إلا إذا كانت مفعلة من إعدادات الموقع.
   لا يوجد توصيل أو سائق أو رسوم توصيل.
*/
(function(){
'use strict';
const KEY='saree_store_carts_v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=v=>typeof window.f==='function'?window.f(v):Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
const state=()=>window.__sareeOrderState||(window.__sareeOrderState={enabled:false,fee:50,carts:JSON.parse(localStorage.getItem(KEY)||'{}')});
function save(){localStorage.setItem(KEY,JSON.stringify(state().carts));}
function cart(storeId){const s=String(storeId);return state().carts[s]||(state().carts[s]=[]);}
function store(id){return (window.stores||[]).find(s=>String(s.id)===String(id));}
function listing(storeId,productId){return (window.prices||[]).find(x=>String(x.store_id)===String(storeId)&&String(x.product_id)===String(productId)&&x.approved!==false);}
function product(id){return (window.products||[]).find(p=>String(p.id)===String(id));}
function wa(st){return st?.whatsapp_url||st?.whatsapp||st?.companies?.whatsapp_url||'';}
function normalizeWa(v){v=String(v||'').trim();if(!v)return '';if(/^https?:\/\//i.test(v))return v;const digits=v.replace(/\D/g,'');return digits?'https://wa.me/'+digits:'';}
function injectStyle(){if(document.getElementById('saree-orders-style'))return;const s=document.createElement('style');s.id='saree-orders-style';s.textContent=`.saree-order-box{margin-top:14px}.saree-cart-item{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px 0;border-bottom:1px solid #29343a}.saree-qty{display:flex;align-items:center;gap:7px}.saree-qty button{border:0;border-radius:8px;background:#1a2429;color:#fff;padding:7px 10px;cursor:pointer}.saree-cart-total{font-size:19px;font-weight:800;color:#35d07f;margin-top:10px}@media(max-width:650px){.saree-cart-item{grid-template-columns:1fr}}`;document.head.appendChild(s);}
async function loadSettings(){
 try{const {data,error}=await supabaseClient.from('saree_feature_settings').select('key,value');if(error)throw error;const map={};(data||[]).forEach(x=>map[x.key]=x.value);state().enabled=String(map.whatsapp_orders_enabled||'false')==='true';state().fee=Math.max(0,Number(map.whatsapp_order_fee||50));}
 catch(e){console.warn('طلبات واتساب settings:',e);state().enabled=false;}
 window.__sareeOrderState=state();
}
function items(storeId){return cart(storeId).map(i=>{const p=product(i.productId),l=listing(storeId,i.productId);return p&&l?{...i,p,l,unit:Number(l.price_new||0),line:Number(l.price_new||0)*Number(i.qty||1)}:null}).filter(Boolean);}
function subtotal(storeId){return items(storeId).reduce((n,x)=>n+x.line,0);}
function countAll(){return Object.values(state().carts).reduce((n,c)=>n+(c||[]).reduce((a,x)=>a+Number(x.qty||0),0),0);}
function updateCount(){const el=document.getElementById('basketCount');if(el)el.textContent=String(countAll());}
function add(storeId,productId){if(!state().enabled)return;const c=cart(storeId);const x=c.find(i=>String(i.productId)===String(productId));if(x)x.qty++;else c.push({productId,qty:1});save();render(storeId);updateCount();}
function change(storeId,productId,delta){const c=cart(storeId),x=c.find(i=>String(i.productId)===String(productId));if(!x)return;x.qty+=delta;if(x.qty<=0){const i=c.indexOf(x);c.splice(i,1);}save();render(storeId);updateCount();}
function clear(storeId){delete state().carts[String(storeId)];save();render(storeId);updateCount();}
function render(storeId){injectStyle();const host=document.getElementById('sareeStoreOrderBox');if(!host)return;if(!state().enabled){host.classList.add('hidden');host.innerHTML='';return;}host.classList.remove('hidden');const st=store(storeId),arr=items(storeId),sub=subtotal(storeId),fee=state().fee,total=sub+fee;host.innerHTML=`<div class="card saree-order-box"><h2>طلب عبر واتساب</h2><p class="muted">هذه السلة خاصة بـ <b>${esc(st?.name||'المتجر')}</b>. لا يوجد توصيل من خلال الموقع.</p>${arr.length?arr.map(x=>`<div class="saree-cart-item"><div><b>${esc(x.p.name)}</b><div class="muted">${fmt(x.unit)} ل.س × ${x.qty} = ${fmt(x.line)} ل.س</div></div><div class="saree-qty"><button onclick="SareeOrders.change('${esc(storeId)}','${esc(x.productId)}',-1)">−</button><b>${x.qty}</b><button onclick="SareeOrders.change('${esc(storeId)}','${esc(x.productId)}',1)">+</button></div></div>`).join(''):`<div class="muted">السلة فارغة. اضغط «أضف للطلب» من منتجات المتجر.</div>`}<div class="muted" style="margin-top:10px">المجموع الفرعي: ${fmt(sub)} ل.س</div><div class="muted">رسم الطلب: ${fmt(fee)} ل.س</div><div class="saree-cart-total">الإجمالي: ${fmt(total)} ل.س</div><div class="actions">${arr.length?`<button class="btn primary" onclick="SareeOrders.send('${esc(storeId)}')">إرسال الطلب عبر واتساب</button><button class="btn secondary" onclick="SareeOrders.clear('${esc(storeId)}')">تفريغ السلة</button>`:''}</div></div>`;}
function orderForm(storeId){const st=store(storeId);const arr=items(storeId);if(!arr.length)return alert('أضف منتجاً واحداً على الأقل إلى سلة هذا المتجر.');const old=state().form||{};const name=prompt('اسم العميل:',old.name||localStorage.getItem('visitor_name')||'');if(name===null)return;const phone=prompt('رقم هاتف العميل (اختياري):',old.phone||'');if(phone===null)return;const notes=prompt('ملاحظات الطلب (اختياري):',old.notes||'');if(notes===null)return;state().form={name:name.trim(),phone:phone.trim(),notes:notes.trim()};localStorage.setItem('saree_order_customer',JSON.stringify(state().form));const sub=subtotal(storeId),fee=state().fee,total=sub+fee;let msg=`طلب جديد من سعرلي سوريا\nالمتجر: ${st?.name||''}\n\n`;arr.forEach((x,i)=>{msg+=`${i+1}. ${x.p.name} — الكمية: ${x.qty} — سعر الوحدة: ${fmt(x.unit)} ل.س — الإجمالي: ${fmt(x.line)} ل.س\n`;});msg+=`\nالمجموع الفرعي: ${fmt(sub)} ل.س\nرسم الطلب: ${fmt(fee)} ل.س\nالإجمالي: ${fmt(total)} ل.س\n\nاسم العميل: ${name.trim()||'غير مذكور'}\nرقم الهاتف: ${phone.trim()||'غير مذكور'}\nملاحظات: ${notes.trim()||'لا توجد'}`;return {msg,total,sub,fee,customer:{name:name.trim(),phone:phone.trim(),notes:notes.trim()}};}
async function send(storeId){const st=store(storeId),url=normalizeWa(wa(st));if(!url)return alert('هذا المتجر لا يملك رابط واتساب للطلبات بعد.');const data=orderForm(storeId);if(!data)return;try{const payload={store_id:storeId,customer_name:data.customer.name||null,customer_phone:data.customer.phone||null,customer_notes:data.customer.notes||null,subtotal:data.sub,request_fee:data.fee,total:data.total,items:items(storeId).map(x=>({product_id:x.productId,name:x.p.name,quantity:x.qty,unit_price:x.unit,line_total:x.line}))};const {error: orderError}=await supabaseClient.rpc('submit_whatsapp_order', payload);if(orderError)throw orderError;}catch(e){console.warn('حفظ طلب واتساب:',e);}window.open(url+(url.includes('?')?'&':'?')+'text='+encodeURIComponent(data.msg),'_blank','noopener');}
function patchStoreDetail(){if(typeof window.renderStoreDetail!=='function'||window.__sareeOrderPatched)return;const original=window.renderStoreDetail;window.renderStoreDetail=function(id){original.apply(this,arguments);setTimeout(()=>{const body=document.getElementById('storeDetailBody');if(!body)return;const host=document.createElement('div');host.id='sareeStoreOrderBox';body.appendChild(host);const st=store(id);const rows=(window.prices||[]).filter(x=>String(x.store_id)===String(id)&&x.approved!==false);const cards=body.querySelectorAll('.storeProductCard');cards.forEach(card=>{const pid=card.dataset.productId;if(pid&&state().enabled){const btn=document.createElement('button');btn.className='btn primary';btn.textContent='أضف للطلب';btn.onclick=()=>add(id,pid);card.querySelector('.actions')?.appendChild(btn)||card.appendChild(btn);}});render(id);},0);};window.__sareeOrderPatched=true;}
async function init(){injectStyle();await loadSettings();patchStoreDetail();updateCount();if(window.__sareeOrderState.enabled&&typeof window.renderStoreDetail==='function'){const active=document.getElementById('storeDetail');if(active?.classList.contains('active')){const m=location.search.match(/[?&]store=([^&]+)/);if(m)window.renderStoreDetail(decodeURIComponent(m[1]));}}}
window.SareeOrders={add,change,clear,send,render,reload:loadSettings};
window.addEventListener('saree:features-updated',()=>{loadSettings().then(()=>{updateCount();const m=location.search.match(/[?&]store=([^&]+)/);if(m&&typeof window.renderStoreDetail==='function')window.renderStoreDetail(decodeURIComponent(m[1]));});});
setTimeout(init,0);
})();
