/* سعرلي سوريا - سلة مستقلة لكل متجر وطلبات واتساب */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=v=>Number(v||0).toLocaleString('ar-SY',{maximumFractionDigits:2});
  const cartsKey='saree_store_carts_v1';
  let settings={enabled:false,fee:50};
  const carts=()=>{try{return JSON.parse(localStorage.getItem(cartsKey)||'{}')}catch(_){return {}}};
  function saveCarts(c){localStorage.setItem(cartsKey,JSON.stringify(c));updateNavCount()}
  function storeCart(storeId){const c=carts();return c[storeId]||{}};
  function setStoreCart(storeId,cart){const c=carts();c[storeId]=cart;saveCarts(c)}
  function updateNavCount(){const total=Object.values(carts()).reduce((n,c)=>n+Object.values(c).reduce((a,x)=>a+Number(x.qty||0),0),0);if($('basketCount'))$('basketCount').textContent=total}
  async function loadSettings(){
    try{const {data,error}=await supabaseClient.from('saree_feature_settings').select('key,value').in('key',['whatsapp_orders_enabled','whatsapp_order_fee']);if(error)throw error;(data||[]).forEach(x=>{if(x.key==='whatsapp_orders_enabled')settings.enabled=String(x.value).toLowerCase()==='true';if(x.key==='whatsapp_order_fee')settings.fee=Number(x.value||0)});}catch(e){console.warn('whatsapp settings',e)}
    window.sareeWhatsappOrdersEnabled=settings.enabled;window.sareeWhatsappOrderFee=settings.fee;
  }
  function rowsForStore(storeId){
    let rows=[];try{rows=(prices||[]).filter(x=>String(x.store_id)===String(storeId))}catch(_){rows=[]}
    return rows.map(r=>({row:r,p:(products||[]).find(p=>String(p.id)===String(r.product_id))})).filter(x=>x.p);
  }
  function add(storeId,productId){if(!settings.enabled)return alert('طلبات واتساب غير مفعلة حالياً.');const row=rowsForStore(storeId).find(x=>String(x.p.id)===String(productId));if(!row)return alert('لم يتم العثور على سعر المنتج في هذا المتجر.');const c=storeCart(storeId);c[productId]=c[productId]||{qty:0,price:Number(row.row.price_new||0),name:row.p.name,unit:row.p.unit||''};c[productId].qty++;setStoreCart(storeId,c);renderStoreCart(storeId)}
  function change(storeId,pid,delta){const c=storeCart(storeId);if(!c[pid])return;c[pid].qty+=delta;if(c[pid].qty<=0)delete c[pid];setStoreCart(storeId,c);renderStoreCart(storeId)}
  function clear(storeId){setStoreCart(storeId,{});renderStoreCart(storeId)}
  function renderStoreCart(storeId){const box=$('sareeStoreCart');if(!box)return;const c=storeCart(storeId),items=Object.entries(c);if(!settings.enabled){box.innerHTML='';box.classList.add('hidden');return}box.classList.remove('hidden');if(!items.length){box.innerHTML='<div class="muted">السلة فارغة. أضف المنتجات من القائمة.</div>';return}let subtotal=0;box.innerHTML=`<h3>سلة هذا المتجر</h3>${items.map(([pid,x])=>{const line=x.qty*x.price;subtotal+=line;return `<div class="saree-cart-line"><div><b>${esc(x.name)}</b>${x.unit?`<div class="muted">${esc(x.unit)}</div>`:''}</div><div class="saree-qty"><button onclick="window.sareeCartChange('${esc(storeId)}','${esc(pid)}',-1)">−</button><b>${x.qty}</b><button onclick="window.sareeCartChange('${esc(storeId)}','${esc(pid)}',1)">+</button></div><div class="saree-line-price">${money(line)} ل.س</div></div>`}).join('')}<div class="muted">المجموع الفرعي: ${money(subtotal)} ل.س</div><div class="muted">رسم الطلب: ${money(settings.fee)} ل.س</div><div class="saree-cart-total">الإجمالي: ${money(subtotal+settings.fee)} ل.س</div><div class="actions"><button class="btn primary" onclick="window.sareeSendWhatsappOrder('${esc(storeId)}')">إرسال الطلب عبر واتساب</button><button class="btn secondary" onclick="window.sareeClearStoreCart('${esc(storeId)}')">تفريغ السلة</button></div>`}
  async function getStore(storeId){let st=(stores||[]).find(s=>String(s.id)===String(storeId));if(st)return st;const {data}=await supabaseClient.from('stores').select('*,companies(id,name,whatsapp_url,verified,active)').eq('id',storeId).maybeSingle();return data}
  function waTarget(st){return st?.whatsapp_url||st?.whatsapp||st?.companies?.whatsapp_url||''}
  function waLink(target,text){if(!target)return '';if(/^https?:\/\//i.test(target)){return target+(target.includes('?')?'&':'?')+'text='+encodeURIComponent(text)}const digits=target.replace(/\D/g,'');return digits?'https://wa.me/'+digits+'?text='+encodeURIComponent(text):''}
  async function send(storeId){if(!settings.enabled)return alert('طلبات واتساب غير مفعلة حالياً.');const st=await getStore(storeId);if(!st)return alert('المتجر غير موجود.');const target=waTarget(st);if(!target)return alert('هذا المتجر لم يضع رابط واتساب للطلبات بعد.');const c=storeCart(storeId),items=Object.entries(c);if(!items.length)return alert('السلة فارغة.');let subtotal=0;const lines=items.map(([pid,x],i)=>{const line=x.qty*x.price;subtotal+=line;return `${i+1}) ${x.name}${x.unit?' ('+x.unit+')':''} × ${x.qty} = ${money(line)} ل.س`});const name=prompt('اسم العميل (اختياري):','')??'';const phone=prompt('رقم هاتف العميل (اختياري):','')??'';const notes=prompt('ملاحظات الطلب (اختياري):','')??'';const total=subtotal+settings.fee;const msg=`طلب من سعرلي سوريا\nالمتجر: ${st.name||''}\n\n${lines.join('\n')}\n\nالمجموع الفرعي: ${money(subtotal)} ل.س\nرسم الطلب: ${money(settings.fee)} ل.س\nالإجمالي: ${money(total)} ل.س\n\nاسم العميل: ${name||'—'}\nهاتف العميل: ${phone||'—'}\nملاحظات: ${notes||'—'}`;try{const {data,error}=await supabaseClient.rpc('submit_whatsapp_order',{p_store_id:storeId,p_customer_name:name||null,p_customer_phone:phone||null,p_customer_notes:notes||null,p_subtotal:subtotal,p_request_fee:settings.fee,p_total:total,p_items:items.map(([pid,x])=>({product_id:pid,name:x.name,unit:x.unit,quantity:x.qty,unit_price:x.price,line_total:x.qty*x.price}))});if(error)throw error;const url=waLink(target,msg);if(!url)throw new Error('رابط واتساب غير صالح.');window.open(url,'_blank','noopener');clear(storeId);alert('تم تجهيز الطلب وإرساله إلى واتساب المتجر.')}catch(e){console.error(e);alert('تعذر تسجيل الطلب: '+(e.message||'خطأ غير معروف'))}}
  window.sareeCartAdd=add;window.sareeCartChange=change;window.sareeClearStoreCart=clear;window.sareeSendWhatsappOrder=send;
  window.renderSareeStoreCart=renderStoreCart;
  const old=window.renderStoreDetail;
  window.renderStoreDetail=async function(id){await old(id);const storeId=id||window.currentStoreId; if(!storeId)return;const body=$('storeDetailBody');if(!body)return;const oldCart=$('sareeStoreCart');if(oldCart)oldCart.remove();const holder=document.createElement('div');holder.id='sareeStoreCart';holder.className='saree-store-cart';const productGrid=$('storeProductsGrid');if(productGrid){productGrid.parentNode.insertBefore(holder,productGrid)}else{body.appendChild(holder)};const rows=rowsForStore(storeId);if(settings.enabled&&rows.length){rows.forEach(({p})=>{const card=[...document.querySelectorAll('#storeProductsGrid [data-product-id]')].find(x=>String(x.dataset.productId)===String(p.id));if(card&&!card.querySelector('[data-saree-add]')){const a=card.querySelector('.actions')||card.appendChild(document.createElement('div'));a.classList.add('actions');const b=document.createElement('button');b.className='btn primary';b.textContent='إضافة للسلة';b.setAttribute('data-saree-add','1');b.onclick=()=>add(storeId,p.id);a.appendChild(b)}})}renderStoreCart(storeId)};
  const oldBasket=window.renderBasket;
  window.renderBasket=function(){if(typeof oldBasket==='function')oldBasket();const box=$('basketList');if(!box)return;const all=carts(),ids=Object.keys(all).filter(k=>Object.keys(all[k]||{}).length);if(!ids.length)return;box.innerHTML=`<div class="card"><h2>سلال المتاجر</h2>${ids.map(id=>{const st=(stores||[]).find(s=>String(s.id)===String(id));const count=Object.values(all[id]).reduce((a,x)=>a+Number(x.qty||0),0);return `<div class="priceRow"><b>${esc(st?.name||'المتجر')}</b><div class="muted">${count} قطع</div><button class="btn primary" onclick="window.openStore('${esc(id)}')">فتح سلة المتجر</button></div>`}).join('')}</div>`};
  loadSettings().then(updateNavCount);setTimeout(()=>loadSettings().then(updateNavCount),1000);updateNavCount();
})();
