/* إدارة مفتاح طلبات واتساب ورسم الطلب */
(function(){'use strict';const C=window.SareeFeatureCore;if(!C)return;const db=C.client,esc=C.escape;let busy=false;
async function isAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='admin';}
async function load(){const {data}=await db.from('saree_feature_settings').select('key,value').in('key',['whatsapp_orders_enabled','whatsapp_order_fee']);const m={};(data||[]).forEach(x=>m[x.key]=x.value);return {enabled:m.whatsapp_orders_enabled==='true',fee:Number(m.whatsapp_order_fee??50)};}
async function save(){if(busy)return;busy=true;try{if(!(await isAdmin()))return alert('هذه الإعدادات للمدير فقط.');const en=document.getElementById('sareeWaToggle').checked;const fee=Math.max(0,Number(document.getElementById('sareeWaFee').value||0));for(const [key,value] of [['whatsapp_orders_enabled',String(en)],['whatsapp_order_fee',String(fee)]]){const {error}=await db.from('saree_feature_settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;}alert('تم حفظ إعدادات طلبات واتساب.');window.dispatchEvent(new Event('saree:features-updated'));}catch(e){alert(e.message)}finally{busy=false;}}
async function inject(){const panel=document.getElementById('adminPanel');if(!panel||document.getElementById('sareeFeatureAdminBox'))return;const s=await load();const box=document.createElement('div');box.id='sareeFeatureAdminBox';box.className='card';box.innerHTML=`<h2>طلبات واتساب</h2><label><input id="sareeWaToggle" type="checkbox" style="width:auto" ${s.enabled?'checked':''}> تفعيل «إرسال الطلب عبر واتساب»</label><label>رسم الطلب بالليرة السورية<input id="sareeWaFee" type="number" min="0" step="1" value="${s.fee}"></label><button class="btn primary" id="sareeWaSave">حفظ</button><p class="muted">عند الإيقاف تختفي وظيفة طلب واتساب من الواجهة، ولا تُحذف بيانات الطلبات السابقة.</p>`;panel.prepend(box);box.querySelector('#sareeWaSave').onclick=save;}
function patch(){if(typeof window.renderAdmin!=='function'||window.__sareeFeatureAdminPatch)return;const orig=window.renderAdmin;window.renderAdmin=async function(){const r=await orig.apply(this,arguments);setTimeout(inject,0);return r;};window.__sareeFeatureAdminPatch=true;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();
})();
