/* سعرلي سوريا — ميزات الشركات وصلاحيات المحتوى */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function ensureColumns(){return;}
async function companyForProduct(p){if(!p)return null;const row=(window.prices||[]).find(x=>String(x.product_id)===String(p.id)); if(!row)return null; const st=(window.stores||[]).find(x=>String(x.id)===String(row.store_id)); return st?.company_id||null;}
function inject(){if(document.getElementById('saree-company-style'))return;const s=document.createElement('style');s.id='saree-company-style';s.textContent='.saree-company-mini{margin-top:10px;padding:9px 11px;border:1px solid #263137;border-radius:12px;background:#10181c;font-size:12px}.saree-company-mini button{margin-top:7px}';document.head.appendChild(s);}
async function companyInfo(id){if(!id)return null;try{const {data}=await supabaseClient.from('companies').select('*').eq('id',id).maybeSingle();return data||null}catch(e){return null}}
async function addPromo(container,p){try{const cid=await companyForProduct(p);if(!cid)return;const c=await companyInfo(cid);if(!c||!c.verified||c.active===false)return;const existing=container.querySelector('.saree-company-mini');if(existing)return;const box=document.createElement('div');box.className='saree-company-mini';box.innerHTML=`🏢 <b>${esc(c.name)}</b><div class="muted">تصفح الشركة المنتجة ومعلوماتها.</div><button class="btn secondary" type="button">تصفح الشركة المنتجة</button>`;box.querySelector('button').onclick=()=>{if(typeof window.openCompany==='function')window.openCompany(c.name)};container.appendChild(box);}catch(e){console.warn('company promo:',e)}}
function patchDetails(){if(typeof window.details!=='function'||window.__sareeCompanyDetailsPatched)return;const old=window.details;window.details=function(id){const r=old.apply(this,arguments);setTimeout(()=>{const root=document.getElementById('productDetail')||document.querySelector('.productDetail');const p=(window.products||[]).find(x=>String(x.id)===String(id));if(root&&p)addPromo(root,p);},0);return r};window.__sareeCompanyDetailsPatched=true;}
async function renderAdminCompanyPermissions(){if(!window.profileData||profileData.role!=='admin')return;const panel=document.getElementById('adminPanel');if(!panel)return;const {data}=await supabaseClient.from('companies').select('id,name,verified,active,allow_product_images,allow_product_questions').order('name');if(!data)return;const box=document.createElement('div');box.className='card';box.id='sareeCompanyPermissions';box.innerHTML='<h2>صلاحيات الشركات</h2><p class="muted">تحدد الإدارة ما يمكن للشركة إظهاره أو استخدامه. هذه الصلاحيات لا تحذف البيانات عند إيقافها.</p>'+data.map(c=>`<div class="priceRow"><b>${esc(c.name)}</b><label><input type="checkbox" data-cid="${esc(c.id)}" data-field="allow_product_images" ${c.allow_product_images!==false?'checked':''}> السماح بصور المنتجات</label><label><input type="checkbox" data-cid="${esc(c.id)}" data-field="allow_product_questions" ${c.allow_product_questions===true?'checked':''}> السماح بأسئلة/ملاحظات المنتج</label></div>`).join('');panel.appendChild(box);box.querySelectorAll('input[data-cid]').forEach(i=>i.onchange=async()=>{const cid=i.dataset.cid,field=i.dataset.field;try{await supabaseClient.from('companies').update({[field]:i.checked,updated_at:new Date().toISOString()}).eq('id',cid);}catch(e){alert(e.message);i.checked=!i.checked;}});}
const oldAdmin=window.renderAdmin;window.renderAdmin=async function(){if(typeof oldAdmin==='function')await oldAdmin.apply(this,arguments);try{await renderAdminCompanyPermissions()}catch(e){console.warn(e)}};
inject();patchDetails();setTimeout(()=>{if(window.profileData?.role==='admin')renderAdminCompanyPermissions().catch(console.warn)},700);
})();
