/* سعرلي سوريا - أفضل الداعمين */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  async function renderPublic(){const box=$('home');if(!box||$('sareeSupportersPublic'))return;try{const {data,error}=await supabaseClient.from('saree_supporters').select('*').eq('visible',true).order('sort_order').limit(20);if(error)throw error;if(!data?.length)return;const section=document.createElement('div');section.id='sareeSupportersPublic';section.className='card';section.innerHTML=`<h2>⭐ أفضل الداعمين</h2><div class="grid">${data.map(x=>`<div class="card">${x.image_url?`<img class="img" style="height:120px;object-fit:cover" src="${esc(x.image_url)}">`:''}<div class="name">${esc(x.name)}</div><div class="muted">${esc(x.description||'')}</div></div>`).join('')}</div>`;box.appendChild(section)}catch(e){console.warn(e)}}
  async function injectAdmin(){if(String(profileData?.role||'').toLowerCase()!=='admin')return;const panel=$('adminPanel');if(!panel||$('sareeSupportersAdmin'))return;const box=document.createElement('div');box.id='sareeSupportersAdmin';box.className='card';box.innerHTML=`<h2>⭐ إدارة أفضل الداعمين</h2><div class="two"><input id="ssName" placeholder="اسم الداعم"><input id="ssDesc" placeholder="وصف مختصر"><input id="ssImage" type="file" accept="image/*"><input id="ssOrder" type="number" value="0" placeholder="الترتيب"></div><button class="btn primary" id="ssAdd">إضافة</button><div id="ssList" style="margin-top:12px"></div>`;panel.appendChild(box);const load=async()=>{const {data}=await supabaseClient.from('saree_supporters').select('*').order('sort_order');$('ssList').innerHTML=(data||[]).map(x=>`<div class="priceRow"><b>${esc(x.name)}</b><div class="muted">${esc(x.description||'')}</div><button class="btn danger" onclick="window.sareeDeleteSupporter('${esc(x.id)}')">حذف</button></div>`).join('')};$('ssAdd').onclick=async()=>{let image=null;const file=$('ssImage').files?.[0];if(file&&window.uploadImage)image=await window.uploadImage(file,'supporters');const {error}=await supabaseClient.from('saree_supporters').insert({name:$('ssName').value.trim(),description:$('ssDesc').value.trim()||null,image_url:image,sort_order:Number($('ssOrder').value||0),visible:true});if(error)return alert(error.message);await load();$('ssName').value='';$('ssDesc').value='';$('ssImage').value=''};load()}
  window.sareeDeleteSupporter=async id=>{if(!confirm('حذف الداعم؟'))return;const {error}=await supabaseClient.from('saree_supporters').delete().eq('id',id);if(error)return alert(error.message);await injectAdmin()};
  const old=window.renderAdmin;if(typeof old==='function')window.renderAdmin=async function(){await old();await injectAdmin()};setTimeout(()=>{renderPublic();injectAdmin()},2200);
})();
