/* الشركات: صلاحيات + نافذة الشركة عند فتح المنتج */
(function(){'use strict';const C=window.SareeFeatureCore;if(!C)return;const db=C.client,esc=C.escape;
function style(){if(document.getElementById('saree-company-style'))return;const s=document.createElement('style');s.id='saree-company-style';s.textContent='.saree-company-promo{border:1px solid #284b39;background:#10231a;border-radius:12px;padding:10px;margin-top:12px}.saree-company-promo button{float:left}.saree-company-products{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}@media(max-width:650px){.saree-company-products{grid-template-columns:1fr}}';document.head.appendChild(s);}
async function companiesForProduct(pid){const {data}=await db.from('price_listings').select('store_id,stores(id,name,company_id,companies(id,name,image_url,verified,active,allow_product_images,allow_product_questions))').eq('product_id',pid).eq('approved',true);const seen=new Set(),out=[];(data||[]).forEach(r=>{const c=r.stores?.companies;if(c?.id&&!seen.has(c.id)&&c.verified&&c.active){seen.add(c.id);out.push(c);}});return out;}
function showPromo(company){let host=document.getElementById('sareeCompanyPromo');if(!host){host=document.createElement('div');host.id='sareeCompanyPromo';}host.className='saree-company-promo';host.innerHTML=`<button class="btn secondary" onclick="this.parentElement.remove()">×</button><b>${esc(company.name)}</b><div class="muted">تصفح الشركة المنتجة</div><div class="actions"><button class="btn primary" onclick="sareeOpenCompany('${company.id}')">فتح صفحة الشركة</button></div>`;const products=document.getElementById('products');products?.parentNode?.insertBefore(host,products);}
window.sareeOpenCompany=async function(id){const {data:c}=await db.from('companies').select('*').eq('id',id).maybeSingle();if(!c)return;const sec=document.getElementById('companyDetail');if(!sec)return;document.getElementById('companyDetailName').textContent=c.name;const {data:stores}=await db.from('stores').select('*').eq('company_id',id).eq('active',true);sec.classList.add('active');document.querySelectorAll('.page').forEach(x=>{if(x!==sec)x.classList.remove('active')});document.getElementById('companyDetailBody').innerHTML=`${c.image_url?`<img class="img" src="${esc(c.image_url)}">`:''}<p class="muted">${esc(c.address||'')}</p><div class="grid">${(stores||[]).map(s=>`<div class="card"><div class="name">${esc(s.name)}</div><div class="muted">${esc(s.city||'')} ${esc(s.area||'')}</div></div>`).join('')||'<div class="card muted">لا توجد متاجر مرتبطة حاليًا.</div>'}</div>`;};
async function patchDetails(){if(typeof window.details!=='function'||window.__sareeCompanyPatch)return;const orig=window.details;window.details=async function(id){const r=orig.apply(this,arguments);setTimeout(async()=>{const cs=await companiesForProduct(id);if(cs[0])showPromo(cs[0]);},100);return r;};window.__sareeCompanyPatch=true;}
async function adminInject(){const panel=document.getElementById('adminPanel');if(!panel||document.getElementById('sareeCompanyPermissions'))return;const {data}=await db.from('companies').select('id,name,allow_product_images,allow_product_questions').order('name');if(!data?.length)return;const box=document.createElement('div');box.id='sareeCompanyPermissions';box.className='card';box.innerHTML='<h2>صلاحيات الشركات</h2>'+data.map(c=>`<div class="priceRow"><b>${esc(c.name)}</b><label><input id="cmpImg_${c.id}" type="checkbox" style="width:auto" ${c.allow_product_images?'checked':''}> السماح بإضافة صور منتجات بدون سعر</label><label><input id="cmpQ_${c.id}" type="checkbox" style="width:auto" ${c.allow_product_questions?'checked':''}> السماح بأسئلة/ملاحظات المنتج</label><button class="btn primary" onclick="sareeSaveCompanyPerm('${c.id}')">حفظ</button></div>`).join('');panel.appendChild(box);}
window.sareeSaveCompanyPerm=async function(id){const {data:{user}}=await db.auth.getUser();const {data:p}=await db.from('profiles').select('role').eq('id',user?.id).maybeSingle();if(p?.role!=='admin')return alert('للمدير فقط.');const {error}=await db.from('companies').update({allow_product_images:document.getElementById('cmpImg_'+id).checked,allow_product_questions:document.getElementById('cmpQ_'+id).checked}).eq('id',id);if(error)return alert(error.message);alert('تم حفظ الصلاحيات.');};
function patchAdmin(){if(typeof window.renderAdmin!=='function'||window.__sareeCompanyAdminPatch)return;const orig=window.renderAdmin;window.renderAdmin=async function(){const r=await orig.apply(this,arguments);setTimeout(adminInject,0);return r;};window.__sareeCompanyAdminPatch=true;}
style();patchDetails();patchAdmin();})();
