/* سعرلي سوريا - سلة مستقلة لكل متجر + طلب واتساب */
(function(){'use strict';
const C=window.SareeFeatureCore;if(!C)return;
const db=C.client, esc=C.escape, fmt=C.fmt, KEY='saree_store_carts_v2';
let enabled=false,fee=50,carts=JSON.parse(localStorage.getItem(KEY)||'{}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(carts));
async function settings(){const {data}=await db.from('saree_feature_settings').select('key,value').in('key',['whatsapp_orders_enabled','whatsapp_order_fee']);const m={};(data||[]).forEach(x=>m[x.key]=x.value);enabled=m.whatsapp_orders_enabled==='true';fee=Math.max(0,Number(m.whatsapp_order_fee??50));return enabled;}
async function store(id){const {data}=await db.from('stores').select('*').eq('id',id).maybeSingle();return data;}
async function productsForStore(id){const {data,error}=await db.from('price_listings').select('product_id,price_new,approved,products(id,name,image_url,unit,brand,category,active)').eq('store_id',id).eq('approved',true).order('price_new');if(error)throw error;return (data||[]).filter(x=>x.products?.active).map(x=>({product:x.products,price:Number(x.price_new||0)}));}
function cart(id){return carts[id]||(carts[id]=[]);}
async function add(id,pid){if(!enabled)return;const c=cart(id),x=c.find(i=>i.productId===pid);if(x)x.qty++;else c.push({productId:pid,qty:1});save();renderStore(id);}
function change(id,pid,d){const c=cart(id),x=c.find(i=>i.productId===pid);if(!x)return;x.qty+=d;if(x.qty<=0)c.splice(c.indexOf(x),1);save();renderStore(id);}
function clear(id){delete carts[id];save();renderStore(id);}
async function renderStore(id){const host=document.getElementById('sareeStoreOrderBox');if(!host)return;if(!enabled){host.classList.add('hidden');host.innerHTML='';return;}host.classList.remove('hidden');const [st,rows]=await Promise.all([store(id),productsForStore(id)]);const c=cart(id);const items=c.map(i=>{const r=rows.find(x=>x.product.id===i.productId);return r?{...r,qty:i.qty,line:r.price*i.qty}:null}).filter(Boolean);const sub=items.reduce((n,x)=>n+x.line,0),total=sub+fee;host.innerHTML=`<div class="card"><h2>طلب عبر واتساب</h2><div class="muted">السلة خاصة بمتجر ${esc(st?.name||'')}.</div>${items.length?items.map(x=>`<div class="priceRow"><b>${esc(x.product.name)}</b><div class="muted">${fmt(x.price)} ل.س × ${x.qty} = ${fmt(x.line)} ل.س</div><div class="actions"><button class="btn secondary" onclick="SareeOrders.change('${id}','${x.product.id}',-1)">−</button><button class="btn secondary" onclick="SareeOrders.change('${id}','${x.product.id}',1)">+</button></div></div>`).join(''):'<div class="notice">السلة فارغة.</div>'}<div class="muted">المجموع الفرعي: ${fmt(sub)} ل.س</div><div class="muted">رسم الطلب: ${fmt(fee)} ل.س</div><div class="price">الإجمالي: ${fmt(total)} ل.س</div>${items.length?'<div class="actions"><button class="btn primary" id="sareeSendOrder">إرسال الطلب عبر واتساب</button><button class="btn secondary" id="sareeClearOrder">تفريغ السلة</button></div>':''}</div>`;host.querySelector('#sareeSendOrder')?.addEventListener('click',()=>send(id,st,items,sub,total));host.querySelector('#sareeClearOrder')?.addEventListener('click',()=>clear(id));}
async function send(id,st,items,sub,total){let wa=C.wa(st?.whatsapp_url||st?.whatsapp);if(!wa)return alert('هذا المتجر لا يملك واتساب للطلبات.');const name=prompt('اسم العميل:',localStorage.getItem('visitor_name')||'')??'';const phone=prompt('رقم الهاتف (اختياري):')??'';const notes=prompt('ملاحظات الطلب (اختياري):')??'';let msg=`طلب من سعرلي سوريا\nالمتجر: ${st.name}\n\n`;items.forEach((x,i)=>msg+=`${i+1}. ${x.product.name} — الكمية: ${x.qty} — سعر الوحدة: ${fmt(x.price)} ل.س — الإجمالي: ${fmt(x.line)} ل.س\n`);msg+=`\nالمجموع الفرعي: ${fmt(sub)} ل.س\nرسم الطلب: ${fmt(fee)} ل.س\nالإجمالي: ${fmt(total)} ل.س\n\nاسم العميل: ${name||'غير مذكور'}\nالهاتف: ${phone||'غير مذكور'}\nملاحظات: ${notes||'لا توجد'}`;try{await db.rpc('submit_whatsapp_order',{p_store_id:id,p_customer_name:name||null,p_customer_phone:phone||null,p_customer_notes:notes||null,p_subtotal:sub,p_request_fee:fee,p_total:total,p_items:items.map(x=>({product_id:x.product.id,name:x.product.name,quantity:x.qty,unit_price:x.price,line_total:x.line}))});}catch(e){console.warn(e);return alert('تعذر حفظ الطلب في الموقع: '+e.message);}window.open(wa+(wa.includes('?')?'&':'?')+'text='+encodeURIComponent(msg),'_blank');}
function enhance(id){let body=document.getElementById('storeDetailBody');if(!body)return;let host=document.getElementById('sareeStoreOrderBox');if(!host){host=document.createElement('div');host.id='sareeStoreOrderBox';body.appendChild(host);}if(!enabled)return renderStore(id);body.querySelectorAll('.storeProductCard').forEach(async card=>{const name=card.querySelector('.name')?.textContent?.trim();if(!name||card.querySelector('.saree-add-order'))return;const rows=await productsForStore(id);const r=rows.find(x=>x.product.name===name);if(!r)return;const b=document.createElement('button');b.className='btn primary saree-add-order';b.textContent='أضف للطلب';b.onclick=()=>add(id,r.product.id);card.appendChild(b);});renderStore(id);}
function patch(){if(typeof window.renderStoreDetail!=='function'||window.__sareeOrdersPatch)return;const orig=window.renderStoreDetail;window.renderStoreDetail=function(id){const r=orig.apply(this,arguments);setTimeout(()=>enhance(id||new URLSearchParams(location.search).get('store')),50);return r;};window.__sareeOrdersPatch=true;}
async function init(){await settings();patch();const id=new URLSearchParams(location.search).get('store');if(id)setTimeout(()=>enhance(id),300);}
window.SareeOrders={add,change,clear,send,reload:settings};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('saree:features-updated',()=>settings().then(()=>{const id=new URLSearchParams(location.search).get('store');if(id)enhance(id);}));
})();
