/* سعرلي سوريا — إعدادات الميزات للمشرف */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const $=id=>document.getElementById(id);
async function read(){const {data,error}=await supabaseClient.from('saree_feature_settings').select('*').order('key');if(error)throw error;return data||[];}
async function save(key,value){const {error}=await supabaseClient.from('saree_feature_settings').upsert({key,value:String(value),updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;window.dispatchEvent(new CustomEvent('saree:features-updated'));}
async function render(){if(!window.profileData||profileData.role!=='admin')return;const panel=$('adminPanel');if(!panel)return;const rows=await read();const map={};rows.forEach(x=>map[x.key]=x.value);const existing=document.getElementById('sareeFeatureAdminBox');if(existing)existing.remove();const box=document.createElement('div');box.id='sareeFeatureAdminBox';box.className='card';box.innerHTML=`<h2>إعدادات الميزات</h2><p class="muted">إيقاف الميزة يخفيها من الواجهة ولا يحذف بياناتها.</p><label><input id="sareeWaOrders" type="checkbox" ${String(map.whatsapp_orders_enabled||'false')==='true'?'checked':''}> طلبات واتساب</label><label>رسم الطلب بالليرة السورية<input id="sareeWaFee" type="number" min="0" step="1" value="${esc(map.whatsapp_order_fee||'50')}"></label><div class="actions"><button class="btn primary" id="sareeSaveFeatures">حفظ الإعدادات</button></div><p id="sareeFeatureMsg" class="muted"></p>`;panel.prepend(box);$('sareeSaveFeatures').onclick=async()=>{const msg=$('sareeFeatureMsg');try{await save('whatsapp_orders_enabled',$('sareeWaOrders').checked?'true':'false');await save('whatsapp_order_fee',Math.max(0,Number($('sareeWaFee').value||0)));msg.textContent='تم حفظ إعدادات الميزات.';}catch(e){msg.textContent='تعذر الحفظ: '+e.message;}};}
const old=window.renderAdmin;window.renderAdmin=async function(){if(typeof old==='function')await old.apply(this,arguments);try{await render();}catch(e){console.warn('feature admin:',e)}};
setTimeout(()=>{if(window.profileData?.role==='admin')render().catch(console.warn)},500);
})();
