-- إحصائيات الزيارات: إجمالي + فريد للموقع والمتاجر والشركات

create table if not exists public.visitor_visits (
  id bigint generated by default as identity primary key,
  visitor_id text,
  visited_at timestamptz not null default now()
);
create index if not exists visitor_visits_visited_at_idx on public.visitor_visits(visited_at);
create index if not exists visitor_visits_visitor_id_idx on public.visitor_visits(visitor_id);
alter table public.visitor_visits enable row level security;
drop policy if exists "public can record visitor visits" on public.visitor_visits;
create policy "public can record visitor visits" on public.visitor_visits for insert to anon, authenticated with check (true);

create table if not exists public.store_visits (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  visitor_id text,
  visited_at timestamptz not null default now()
);
create index if not exists store_visits_store_id_idx on public.store_visits(store_id);
create index if not exists store_visits_visited_at_idx on public.store_visits(visited_at);
create index if not exists store_visits_visitor_id_idx on public.store_visits(visitor_id);
alter table public.store_visits enable row level security;
drop policy if exists "public can record store visits" on public.store_visits;
create policy "public can record store visits" on public.store_visits for insert to anon, authenticated with check (true);

create table if not exists public.company_visits (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  visitor_id text,
  visited_at timestamptz not null default now()
);
create index if not exists company_visits_company_id_idx on public.company_visits(company_id);
create index if not exists company_visits_visited_at_idx on public.company_visits(visited_at);
create index if not exists company_visits_visitor_id_idx on public.company_visits(visitor_id);
alter table public.company_visits enable row level security;
drop policy if exists "public can record company visits" on public.company_visits;
create policy "public can record company visits" on public.company_visits for insert to anon, authenticated with check (true);

create or replace function public.admin_visitor_count() returns bigint language sql security definer set search_path=public as $$ select count(*)::bigint from public.visitor_visits; $$;
create or replace function public.admin_unique_visitor_count() returns bigint language sql security definer set search_path=public as $$ select count(distinct visitor_id)::bigint from public.visitor_visits where visitor_id is not null and visitor_id<>''; $$;

create or replace function public.merchant_store_visit_counts(p_store_id uuid) returns jsonb language sql security definer set search_path=public as $$
  select jsonb_build_object('total_visits',count(*)::bigint,'unique_visitors',count(distinct visitor_id)::bigint) from public.store_visits where store_id=p_store_id and visitor_id is not null;
$$;

create or replace function public.admin_store_visitor_counts() returns table(store_id uuid,total_visits bigint,unique_visitors bigint) language sql security definer set search_path=public as $$
  select s.id,count(v.id)::bigint,count(distinct v.visitor_id)::bigint from public.stores s left join public.store_visits v on v.store_id=s.id group by s.id;
$$;

create or replace function public.company_visit_counts(p_company_id uuid) returns jsonb language sql security definer set search_path=public as $$
  select jsonb_build_object('total_visits',count(*)::bigint,'unique_visitors',count(distinct visitor_id)::bigint) from public.company_visits where company_id=p_company_id;
$$;

create or replace function public.admin_company_visitor_counts() returns table(company_id uuid,total_visits bigint,unique_visitors bigint) language sql security definer set search_path=public as $$
  select c.id,count(v.id)::bigint,count(distinct v.visitor_id)::bigint from public.companies c left join public.company_visits v on v.company_id=c.id group by c.id;
$$;

revoke all on function public.admin_visitor_count() from public;
revoke all on function public.admin_unique_visitor_count() from public;
revoke all on function public.merchant_store_visit_counts(uuid) from public;
revoke all on function public.admin_store_visitor_counts() from public;
revoke all on function public.company_visit_counts(uuid) from public;
revoke all on function public.admin_company_visitor_counts() from public;
grant execute on function public.admin_visitor_count() to authenticated;
grant execute on function public.admin_unique_visitor_count() to authenticated;
grant execute on function public.merchant_store_visit_counts(uuid) to authenticated;
grant execute on function public.admin_store_visitor_counts() to authenticated;
grant execute on function public.company_visit_counts(uuid) to anon, authenticated;
grant execute on function public.admin_company_visitor_counts() to authenticated;

notify pgrst,'reload schema';
