-- سعرلي سوريا — visits_complete.sql
-- نسخة مصححة ومتوافقة مع الدوال القديمة الموجودة في المشروع.
-- شغّل الملف كاملًا مرة واحدة من Supabase > SQL Editor.
--
-- مهم:
-- هذا الملف يعالج خطأ:
-- ERROR 42P13: cannot change return type of existing function
-- عن طريق حذف الدوال القديمة قبل إعادة إنشائها.
--
-- ملاحظة:
-- إجمالي زيارات المتجر يحتاج أن يسجل كل فتح للمتجر كسطر مستقل.
-- لذلك نستخدم store_visit_events بدل نظام upsert القديم للزائر الفريد.

begin;

-- =========================================================
-- 1) زيارات الموقع: كل زيارة = سجل مستقل
-- =========================================================

create table if not exists public.visitor_visits (
  id bigint generated by default as identity primary key,
  visitor_id text,
  visited_at timestamptz not null default now()
);

create index if not exists visitor_visits_visited_at_idx
  on public.visitor_visits(visited_at);

create index if not exists visitor_visits_visitor_id_idx
  on public.visitor_visits(visitor_id);

alter table public.visitor_visits enable row level security;

drop policy if exists "public can record visitor visits"
  on public.visitor_visits;

create policy "public can record visitor visits"
on public.visitor_visits
for insert
to anon, authenticated
with check (true);


-- =========================================================
-- 2) زيارات المتاجر: كل فتح للمتجر = سجل مستقل
-- =========================================================

create table if not exists public.store_visit_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  visitor_id text,
  visited_at timestamptz not null default now()
);

create index if not exists store_visit_events_store_id_idx
  on public.store_visit_events(store_id);

create index if not exists store_visit_events_visited_at_idx
  on public.store_visit_events(visited_at);

create index if not exists store_visit_events_visitor_id_idx
  on public.store_visit_events(visitor_id);

alter table public.store_visit_events enable row level security;

drop policy if exists "public can record store visit events"
  on public.store_visit_events;

create policy "public can record store visit events"
on public.store_visit_events
for insert
to anon, authenticated
with check (true);


-- =========================================================
-- 3) زيارات الشركات: كل فتح/زيارة للشركة = سجل مستقل
-- =========================================================

create table if not exists public.company_visit_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  visitor_id text,
  visited_at timestamptz not null default now()
);

create index if not exists company_visit_events_company_id_idx
  on public.company_visit_events(company_id);

create index if not exists company_visit_events_visited_at_idx
  on public.company_visit_events(visited_at);

create index if not exists company_visit_events_visitor_id_idx
  on public.company_visit_events(visitor_id);

alter table public.company_visit_events enable row level security;

drop policy if exists "public can record company visit events"
  on public.company_visit_events;

create policy "public can record company visit events"
on public.company_visit_events
for insert
to anon, authenticated
with check (true);


-- =========================================================
-- 4) تسجيل زيارة متجر عبر RPC
-- =========================================================

drop function if exists public.record_store_visit(uuid);

create or replace function public.record_store_visit(
  p_store_id uuid,
  p_visitor_id text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_store_id is null then
    return;
  end if;

  insert into public.store_visit_events(store_id, visitor_id)
  values (p_store_id, nullif(trim(coalesce(p_visitor_id,'')), ''));
end;
$$;

revoke all on function public.record_store_visit(uuid,text) from public;
grant execute on function public.record_store_visit(uuid,text) to anon, authenticated;


-- =========================================================
-- 5) تسجيل زيارة شركة عبر RPC
-- =========================================================

drop function if exists public.record_company_visit(uuid);

create or replace function public.record_company_visit(
  p_company_id uuid,
  p_visitor_id text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_company_id is null then
    return;
  end if;

  insert into public.company_visit_events(company_id, visitor_id)
  values (p_company_id, nullif(trim(coalesce(p_visitor_id,'')), ''));
end;
$$;

revoke all on function public.record_company_visit(uuid,text) from public;
grant execute on function public.record_company_visit(uuid,text) to anon, authenticated;


-- =========================================================
-- 6) إجمالي الموقع
-- =========================================================

drop function if exists public.admin_visitor_count();

create or replace function public.admin_visitor_count()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint
  from public.visitor_visits;
$$;

revoke all on function public.admin_visitor_count() from public;
grant execute on function public.admin_visitor_count() to authenticated;


-- =========================================================
-- 7) الزوار الفريدون للموقع
-- =========================================================

drop function if exists public.admin_unique_visitor_count();

create or replace function public.admin_unique_visitor_count()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(distinct visitor_id)::bigint
  from public.visitor_visits
  where visitor_id is not null
    and trim(visitor_id) <> '';
$$;

revoke all on function public.admin_unique_visitor_count() from public;
grant execute on function public.admin_unique_visitor_count() to authenticated;


-- =========================================================
-- 8) إحصائيات المتاجر للمدير
--
-- نحذف الدالة القديمة أولًا لأن نوع الإرجاع قديم.
-- =========================================================

drop function if exists public.admin_store_visitor_counts();

create or replace function public.admin_store_visitor_counts()
returns table (
  store_id uuid,
  visitor_count bigint,
  total_visits bigint,
  unique_visitors bigint
)
language sql
security definer
set search_path = public
as $$
  select
    s.id as store_id,
    count(v.id)::bigint as visitor_count,
    count(v.id)::bigint as total_visits,
    count(distinct v.visitor_id)::bigint as unique_visitors
  from public.stores s
  left join public.store_visit_events v
    on v.store_id = s.id
  group by s.id
  order by s.name;
$$;

revoke all on function public.admin_store_visitor_counts() from public;
grant execute on function public.admin_store_visitor_counts() to authenticated;


-- =========================================================
-- 9) إحصائيات متجر للتاجر
-- =========================================================

drop function if exists public.merchant_store_visitor_count(uuid);
drop function if exists public.merchant_store_visitor_stats(uuid);

create or replace function public.merchant_store_visitor_count(
  p_store_id uuid
)
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint
  from public.store_visit_events v
  where v.store_id = p_store_id
    and exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'store'
        and p.store_id = p_store_id
    );
$$;

create or replace function public.merchant_store_visitor_stats(
  p_store_id uuid
)
returns table (
  total_visits bigint,
  unique_visitors bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(v.id)::bigint as total_visits,
    count(distinct v.visitor_id)::bigint as unique_visitors
  from public.store_visit_events v
  where v.store_id = p_store_id
    and exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'store'
        and p.store_id = p_store_id
    );
$$;

revoke all on function public.merchant_store_visitor_count(uuid) from public;
revoke all on function public.merchant_store_visitor_stats(uuid) from public;

grant execute on function public.merchant_store_visitor_count(uuid) to authenticated;
grant execute on function public.merchant_store_visitor_stats(uuid) to authenticated;


-- =========================================================
-- 10) إحصائيات الشركات للمدير
-- =========================================================

drop function if exists public.admin_company_visitor_counts();

create or replace function public.admin_company_visitor_counts()
returns table (
  company_id uuid,
  visitor_count bigint,
  total_visits bigint,
  unique_visitors bigint
)
language sql
security definer
set search_path = public
as $$
  select
    c.id as company_id,
    count(v.id)::bigint as visitor_count,
    count(v.id)::bigint as total_visits,
    count(distinct v.visitor_id)::bigint as unique_visitors
  from public.companies c
  left join public.company_visit_events v
    on v.company_id = c.id
  group by c.id
  order by c.name;
$$;

revoke all on function public.admin_company_visitor_counts() from public;
grant execute on function public.admin_company_visitor_counts() to authenticated;


-- =========================================================
-- 11) إحصائيات شركة عامة/لصاحب الصلاحية
--
-- لا نفترض وجود company_id داخل profiles لأن schema الحالي
-- الذي راجعناه لا يحتوي على هذا الربط.
-- لذلك هذه الدالة للمدير فقط.
-- =========================================================

drop function if exists public.admin_company_visitor_stats(uuid);

create or replace function public.admin_company_visitor_stats(
  p_company_id uuid
)
returns table (
  total_visits bigint,
  unique_visitors bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(v.id)::bigint as total_visits,
    count(distinct v.visitor_id)::bigint as unique_visitors
  from public.company_visit_events v
  where v.company_id = p_company_id
    and public.is_admin();
$$;

revoke all on function public.admin_company_visitor_stats(uuid) from public;
grant execute on function public.admin_company_visitor_stats(uuid) to authenticated;


-- =========================================================
-- 12) إصلاح/تحديث دوال الإحصائيات القديمة المحتملة
-- =========================================================

-- إذا كان الجدول القديم موجودًا، نتركه كما هو حتى لا نحذف
-- بيانات الزوار الفريدة القديمة.
-- البيانات الجديدة للإجمالي تسجل في الجداول الجديدة أعلاه.


-- =========================================================
-- 13) إعادة تحميل PostgREST schema
-- =========================================================

notify pgrst, 'reload schema';

commit;
